
services:
  backend:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=devlife;Username=postgres;Password=postgres
      - MongoSettings__ConnectionString=mongodb://mongo:27017
      - MongoSettings__Database=devlife
    depends_on:
      - postgres
      - mongo
      - redis

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: devlife
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  redis:
    image: redis
    ports:
      - "6379:6379"
